### ISSUE TITLE
Index Error on v1.0

### ISSUE THREAD

**Issue by se1ecis** [mikhail-vlasenko/Tetris-AI#10]
Forgive me for asking this question a second time.
When I run the program I get the following error
Can you tell me how to deal with it?

Traceback (most recent call last):
  File "C:\Users\SK\Downloads\Tetris-AI-1.0\main.py", line 51, in <module>
    main()
  File "C:\Users\SK\Downloads\Tetris-AI-1.0\main.py", line 16, in main
    field, next_piece = get_field()
  File "C:\Users\SK\Downloads\Tetris-AI-1.0\scan_field.py", line 60, in get_field
    arr += field[r1][:, r2]
IndexError: index 0 is out of bounds for axis 1 with size 0

**Comment by mikhail-vlasenko** [comment]
it seems that the return array of `consts.get_field_from_screen(img)` is empty, which might happen because your `Consts` are not properly set up
