### ISSUE TITLE
Does this bot work on tetr.io? If so, how do I get it to work on tetr.io

### ISSUE THREAD

**Issue by NameLmao** [mikhail-vlasenko/Tetris-AI#4]
Does this bot work on tetr.io? If so, how do I get it to work on tetr.io

**Comment by mikhail-vlasenko** [comment]
It should, with a few modifications. All you should do is 
1. Add a `Consts` instance with pixels for your screen to `data.py` (take a screenshot and open it in paint to get the pixel positions)
2. Change `consts` in `scan_field.py` to use your new instance
3. Change hex codes at the beginning of `direct_keys.py`, because tetr.io uses arrows and we use WASD. For hex code reference, use table 90 (first page) [here](https://studylib.net/doc/10745497/appendix-c--keyboard-scan-codes), or, what seems to be a more common way, but which didn't work for us, key codes from [here](https://stackoverflow.com/a/11910555/10919379)

Good luck!

**Comment by NameLmao** [comment]
How much of the screen should I cover with the screenshots?

**Comment by mikhail-vlasenko** [comment]
take 1 screenshot of the whole screen to see where the borders of the tetris field are

**Comment by NameLmao** [comment]
Ok, thank you.

**Comment by NameLmao** [comment]
Sorry for the followup, but what exactly is the order required for the numbers in changings the consts and what do the numbers represent in this line? "(225, 888, 115, 441, 315, 505, 450, 475)"

**Comment by mikhail-vlasenko** [comment]
as written in the class constructor, `top, bottom, left, right, next_top, next_bottom, next_left, next_right` where the first 4 are for the playing grid, and the last 4 are for recognizing next pieces

**Comment by NameLmao** [comment]
Oh, thank you, I was a bit confused about what the “next” meant

**Comment by NameLmao** [comment]
Does the hold grid include the playing grid?

**Comment by NameLmao** [comment]
C:\Users\>"C:\Users\\Downloads\Tetris-AI-master (1)\Tetris-AI-master\main.py"
Traceback (most recent call last):
  File "C:\Users\\Downloads\Tetris-AI-master (1)\Tetris-AI-master\main.py", line 51, in <module>
    main()
  File "C:\Users\\Downloads\Tetris-AI-master (1)\Tetris-AI-master\main.py", line 16, in main
    field, next_piece = get_field()
  File "C:\Users\\Downloads\Tetris-AI-master (1)\Tetris-AI-master\scan_field.py", line 60, in get_field
    arr += field[r1][:, r2]
IndexError: index 147 is out of bounds for axis 1 with size 147

Got this error when trying to run on Tetr.io, i suspect it is the pieces displaying at the top which confuses the ai because its not like jstris where the piece shows up at the top of the field but on tetr.io it shows up a few blocks above

**Comment by mikhail-vlasenko** [comment]
hold is not included in the playing grid. 

pieces displayed on top is bad indeed, you might want to increase field height so it sees new pieces entirely. you will probably need to change grid resolution as well, in this case.

the error occurs before the actual playing algorithm starts. Your screen resolution might be different, or something else, debug the arrays, you can also use the `print_image` function from this file. 
it doesn't matter how, as long as you give the correct field array to the algorithm, it will work

**Comment by NameLmao** [comment]
For the playing grid coordinates, which coordinates do I use, pixel locations using distance from the top left corner?
